/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fckfood;

import models.ThucDon;
import models.User;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Locale;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.border.Border;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;
import javax.swing.plaf.basic.BasicButtonUI;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import models.HoaDon;

/**
 *
 * @author NhokKiZ
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    int chuotX;
    int chuotY;
    String uname ="";
    String uid;
    long tongtien;
    public ThucDon sp = new ThucDon();
    GioHang gh = new GioHang();
    public DefaultTableModel tbMonchinh = new DefaultTableModel();
    public DefaultTableModel tbMonphu = new DefaultTableModel();
    public DefaultTableModel tbNuoc = new DefaultTableModel();
    String []spcol = {"Mã sản phẩm","Tên món","Đơn giá","Số lượng tồn"};
    
    public MainMenu() {
        this.uname = User.name();
        this.uid = User.userName();
        try {
            updateTb();
        } catch (SQLException ex) {}
        initComponents();
        jTbChinh.getTableHeader();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    int isClicked=1;
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        displayName = new javax.swing.JLabel();
        menuSys = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        menuOrder = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        menuManager = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        menuLogout = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        minimizeBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelChinh = new javax.swing.JPanel();
        jTbChinh = new javax.swing.JTable();
        btnAddChinh = new javax.swing.JButton();
        panelPhu = new javax.swing.JPanel();
        jTbPhu = new javax.swing.JTable();
        btnAddPhu = new javax.swing.JButton();
        panelNuoc = new javax.swing.JPanel();
        jTbNuoc = new javax.swing.JTable();
        btnAddNuoc = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbTien = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnHuy = new javax.swing.JButton();
        btnThanhtoan = new javax.swing.JButton();
        btnCapnhat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(200, 100));
        setName("Menu"); // NOI18N
        setUndecorated(true);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MetroLookAndFeel ui = new MetroLookAndFeel();

        jPanel3.setBackground(new java.awt.Color(220, 40, 56));
        jPanel3.setToolTipText("");
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 714));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Xin chào");

        displayName.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        displayName.setForeground(new java.awt.Color(255, 255, 255));
        displayName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        displayName.setText("admin");
        displayName.setText(uname);

        menuSys.setBackground(new java.awt.Color(220, 40, 56));
        menuSys.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        menuSys.setToolTipText("");
        menuSys.setPreferredSize(new java.awt.Dimension(310, 70));
        menuSys.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSysMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuSysMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuSysMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Hệ thống");

        javax.swing.GroupLayout menuSysLayout = new javax.swing.GroupLayout(menuSys);
        menuSys.setLayout(menuSysLayout);
        menuSysLayout.setHorizontalGroup(
            menuSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuSysLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(115, 115, 115))
        );
        menuSysLayout.setVerticalGroup(
            menuSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuSysLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuOrder.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        menuOrder.setToolTipText("");
        menuOrder.setPreferredSize(new java.awt.Dimension(338, 70));
        menuOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuOrderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuOrderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuOrderMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Order món ăn");
        jLabel4.setFocusable(false);

        javax.swing.GroupLayout menuOrderLayout = new javax.swing.GroupLayout(menuOrder);
        menuOrder.setLayout(menuOrderLayout);
        menuOrderLayout.setHorizontalGroup(
            menuOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addGap(115, 115, 115))
        );
        menuOrderLayout.setVerticalGroup(
            menuOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setLabelFor(this);
        jLabel1.setText(" FCKFOOD");
        jLabel1.setAlignmentX(200.0F);
        jLabel1.setAlignmentY(100.0F);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel1.setBounds(5, 10, 631, 36);
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        menuManager.setBackground(new java.awt.Color(220, 40, 56));
        menuManager.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        menuManager.setToolTipText("");
        menuManager.setPreferredSize(new java.awt.Dimension(310, 70));
        menuManager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuManagerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuManagerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuManagerMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Quản lý");

        javax.swing.GroupLayout menuManagerLayout = new javax.swing.GroupLayout(menuManager);
        menuManager.setLayout(menuManagerLayout);
        menuManagerLayout.setHorizontalGroup(
            menuManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuManagerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(115, 115, 115))
        );
        menuManagerLayout.setVerticalGroup(
            menuManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuManagerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Developed by Kiz with ♥");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("® Client");

        menuLogout.setBackground(new java.awt.Color(255, 153, 102));
        menuLogout.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        menuLogout.setToolTipText("");
        menuLogout.setPreferredSize(new java.awt.Dimension(310, 70));
        menuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuLogoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuLogoutMousePressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Logout");

        javax.swing.GroupLayout menuLogoutLayout = new javax.swing.GroupLayout(menuLogout);
        menuLogout.setLayout(menuLogoutLayout);
        menuLogoutLayout.setHorizontalGroup(
            menuLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(115, 115, 115))
        );
        menuLogoutLayout.setVerticalGroup(
            menuLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuManager, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                    .addComponent(menuSys, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(displayName, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(menuOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(50, 50, 50)
                .addComponent(jLabel3)
                .addGap(10, 10, 10)
                .addComponent(displayName)
                .addGap(40, 40, 40)
                .addComponent(menuOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(menuManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(menuSys, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menuLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(220, 40, 56));
        jPanel4.setPreferredSize(new java.awt.Dimension(960, 48));

        jPanel2.setPreferredSize(new java.awt.Dimension(86, 35));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        minimizeBtn.setBackground(new java.awt.Color(220, 40, 56));
        minimizeBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        minimizeBtn.setText("_");
        ui.Mau("trang");
        minimizeBtn.setUI(ui);
        minimizeBtn.setMaximumSize(new java.awt.Dimension(43, 35));
        minimizeBtn.setMinimumSize(new java.awt.Dimension(43, 35));
        minimizeBtn.setPreferredSize(new java.awt.Dimension(43, 35));
        minimizeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeBtnActionPerformed(evt);
            }
        });
        jPanel2.add(minimizeBtn);

        closeBtn.setBackground(new java.awt.Color(255, 51, 51));
        closeBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        closeBtn.setText("X");
        closeBtn.setToolTipText("");
        ui.Mau("Do");
        closeBtn.setUI(ui);
        closeBtn.setBorderPainted(false);
        closeBtn.setMaximumSize(new java.awt.Dimension(43, 35));
        closeBtn.setMinimumSize(new java.awt.Dimension(43, 35));
        closeBtn.setPreferredSize(new java.awt.Dimension(43, 35));
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        jPanel2.add(closeBtn);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(973, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(220, 40, 46), 1, true));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        String spcol[] = {"Mã sản phẩm","Tên món","Đơn giá","Số lượng tồn"};

        panelChinh.setBackground(new java.awt.Color(255, 255, 255));

        jTbChinh.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTbChinh.setDefaultEditor(Object.class, null);
        jTbChinh.setModel(tbMonchinh);
        jTbChinh.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTbChinh.setRowHeight(26);
        tbMonchinh.setColumnIdentifiers(spcol);
        jTbChinh.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTbChinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbChinhMouseClicked(evt);
            }
        });

        btnAddChinh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddChinh.setText("Thêm");
        btnAddChinh.setEnabled(false);
        btnAddChinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddChinhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelChinhLayout = new javax.swing.GroupLayout(panelChinh);
        panelChinh.setLayout(panelChinhLayout);
        panelChinhLayout.setHorizontalGroup(
            panelChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTbChinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1034, Short.MAX_VALUE)
            .addGroup(panelChinhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddChinh, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelChinhLayout.setVerticalGroup(
            panelChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChinhLayout.createSequentialGroup()
                .addComponent(jTbChinh, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAddChinh, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Món chính", panelChinh);

        panelPhu.setBackground(new java.awt.Color(255, 255, 255));

        jTbPhu.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTbChinh.setDefaultEditor(Object.class, null);
        jTbPhu.setModel(tbMonphu);
        jTbPhu.setRowHeight(26);
        tbMonphu.setColumnIdentifiers(spcol);
        jTbPhu.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTbPhu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbPhuMouseClicked(evt);
            }
        });

        btnAddPhu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddPhu.setText("Thêm");
        btnAddPhu.setEnabled(false);
        btnAddPhu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPhuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPhuLayout = new javax.swing.GroupLayout(panelPhu);
        panelPhu.setLayout(panelPhuLayout);
        panelPhuLayout.setHorizontalGroup(
            panelPhuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTbPhu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1034, Short.MAX_VALUE)
            .addGroup(panelPhuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddPhu, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPhuLayout.setVerticalGroup(
            panelPhuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPhuLayout.createSequentialGroup()
                .addComponent(jTbPhu, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAddPhu, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Món ăn kèm", panelPhu);

        panelNuoc.setBackground(new java.awt.Color(255, 255, 255));

        jTbNuoc.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTbChinh.setDefaultEditor(Object.class, null);
        jTbNuoc.setModel(tbNuoc);
        jTbNuoc.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTbNuoc.setRowHeight(26);
        jTbNuoc.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTbNuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbNuocMouseClicked(evt);
            }
        });

        btnAddNuoc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddNuoc.setText("Thêm");
        btnAddNuoc.setEnabled(false);
        btnAddNuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNuocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNuocLayout = new javax.swing.GroupLayout(panelNuoc);
        panelNuoc.setLayout(panelNuocLayout);
        panelNuocLayout.setHorizontalGroup(
            panelNuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTbNuoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1034, Short.MAX_VALUE)
            .addGroup(panelNuocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddNuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelNuocLayout.setVerticalGroup(
            panelNuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNuocLayout.createSequentialGroup()
                .addComponent(jTbNuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAddNuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Nước", panelNuoc);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1034, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 684, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Combo", jPanel7);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Tổng tiền :");

        lbTien.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        lbTien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbTien.setText("0");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("VNĐ");

        btnHuy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnHuy.setText("Huỷ đơn");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnThanhtoan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnThanhtoan.setText("Thanh Toán");
        btnThanhtoan.setEnabled(false);
        btnThanhtoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhtoanActionPerformed(evt);
            }
        });

        btnCapnhat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCapnhat.setText("Cập nhật");
        btnCapnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapnhatActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jTabbedPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lbTien, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnHuy, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnThanhtoan, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnCapnhat, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnThanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCapnhat, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1061, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(269, 269, 269)
                                .addComponent(lbTien)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11))))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 901, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lbTien)
                    .addComponent(jLabel11))
                .addGap(34, 34, 34)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThanhtoan, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(btnCapnhat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DRAG_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void minimizeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeBtnActionPerformed
        // TODO add your handling code here:
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeBtnActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        // Close Tool
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_closeBtnActionPerformed

    private void menuOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuOrderMouseClicked
        // TODO add your handling code here:
        
        MenuBtn_Clicked("order");
        
//jLayeredPane1.show();
    }//GEN-LAST:event_menuOrderMouseClicked

    private void menuOrderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuOrderMouseEntered
        // TODO add your handling code here:
        if(isClicked!=1)
            menuOrder.setBackground(new Color(177,40,56));
                        
    }//GEN-LAST:event_menuOrderMouseEntered

    private void menuOrderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuOrderMouseExited
        if(isClicked!=1)
            menuOrder.setBackground(new Color(220,40,56));
        
    }//GEN-LAST:event_menuOrderMouseExited

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        chuotX = evt.getX();
        chuotY = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        int toadoX = evt.getXOnScreen();
        int toadoY = evt.getYOnScreen();
        this.setLocation(toadoX - chuotX, toadoY - chuotY);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void menuManagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuManagerMouseClicked
        MenuBtn_Clicked("manager");
        Manager mg;
        try {
            mg = new Manager();
            mg.show();
        } catch (SQLException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.dispose();
        //jLayeredPane1.show();
    }//GEN-LAST:event_menuManagerMouseClicked

    private void menuManagerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuManagerMouseEntered
        // TODO add your handling code here:
        if(isClicked!=2)
            menuManager.setBackground(new Color(177,40,56));
    }//GEN-LAST:event_menuManagerMouseEntered

    private void menuManagerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuManagerMouseExited
        
        if(isClicked!=2)
            menuManager.setBackground(new Color(220,40,56));
        
    }//GEN-LAST:event_menuManagerMouseExited

    private void menuSysMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSysMouseClicked
        // TODO add your handling code here:
        MenuBtn_Clicked("sys");
        //this.setVisible(false);
        //new Login().setVisible(true);
        
    }//GEN-LAST:event_menuSysMouseClicked

    private void menuSysMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSysMouseEntered
         if(isClicked!=3)
            menuSys.setBackground(new Color(177,40,56));
    }//GEN-LAST:event_menuSysMouseEntered

    private void menuSysMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSysMouseExited
        if(isClicked!=3)
            menuSys.setBackground(new Color(220,40,56));
    }//GEN-LAST:event_menuSysMouseExited

    private void btnAddChinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddChinhActionPerformed
        // TODO add your handling code here:
         //int row[];
        //row = jTbChinh.getSelectedRows();
        int clicked = 0;
        int tien=0;
        Vector a = (Vector) tbMonchinh.getDataVector().elementAt(jTbChinh.getSelectedRow());
        a.set(3, "1");
        gh.AddGiohang(a);
        if(clicked==0){
        clicked++;
        gh.show();
        }
        CapNhatTien();
        //jTbChinh.getValueAt(row[0]);
    }//GEN-LAST:event_btnAddChinhActionPerformed

    private void btnAddPhuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPhuActionPerformed
        int clicked = 0;
        int tien=0;
        Vector a = (Vector) tbMonphu.getDataVector().elementAt(jTbPhu.getSelectedRow());
        a.set(3, "1");
        gh.AddGiohang(a);
        if(clicked==0){
        clicked++;
        gh.show();
        }
        CapNhatTien();

    }//GEN-LAST:event_btnAddPhuActionPerformed

    private void btnAddNuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNuocActionPerformed
        int clicked = 0;
        int tien=0;
        Vector a = (Vector) tbNuoc.getDataVector().elementAt(jTbNuoc.getSelectedRow());
        a.set(3, "1");
        gh.AddGiohang(a);
        if(clicked==0){
        clicked++;
        gh.show();
        }
        CapNhatTien();
    }//GEN-LAST:event_btnAddNuocActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        btnThanhtoan.setEnabled(false);
        btnAddChinh.setEnabled(false);
        btnAddPhu.setEnabled(false);
        btnAddNuoc.setEnabled(false);
        int row=gh.tbGiohang.getRowCount();
        for(int i=row-1;i>=0;i--){         
        gh.tbGiohang.removeRow(i);
        }
        gh.dispose();
        SetTien(0);
        try {
            updateTb();
        } catch (SQLException ex) {}
    }//GEN-LAST:event_btnHuyActionPerformed

    private void menuLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseClicked
        // TODO add your handling code here:
        Login lg = new Login();
        User.Logout();
        this.dispose();
        lg.show();
    }//GEN-LAST:event_menuLogoutMouseClicked

    private void menuLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseEntered
        // TODO add your handling code here:
        menuLogout.setBackground(new Color(221,91,37));
    }//GEN-LAST:event_menuLogoutMouseEntered

    private void menuLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseExited
        menuLogout.setBackground(new Color(255,153,102));
    }//GEN-LAST:event_menuLogoutMouseExited

    private void btnThanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhtoanActionPerformed
        if(gh.click!=0)
            btnCapnhat.doClick();
        else{
        HoaDon hd = new HoaDon();
        int row = gh.tbGiohang.getRowCount();
        try {
            hd.InsertHD(uid,tongtien);
            int mahd = hd.GetMaHD();
            for(int i=0;i<row;i++){
                hd.InsertCTHD(mahd,gh.tbGiohang.getValueAt(i, 0).toString(), Integer.parseInt(gh.tbGiohang.getValueAt(i, 3).toString()));
            }
            JOptionPane.showMessageDialog(this,"\n Đã thanh toán thành công ! \n\n","Giao dịch hoàn thành",JOptionPane.INFORMATION_MESSAGE);
            btnHuy.doClick();
            updateTb();
        }
        catch (SQLException ex) {
            //
        }
        }
    }//GEN-LAST:event_btnThanhtoanActionPerformed

    private void btnCapnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapnhatActionPerformed
        // TODO add your handling code here:
        CapNhatTien();
        try {
            updateTb();
        } catch (SQLException ex) {}
    }//GEN-LAST:event_btnCapnhatActionPerformed

    private void menuLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMousePressed
        // TODO add your handling code here:
        menuLogout.setBackground(new Color(255,208,132));
    }//GEN-LAST:event_menuLogoutMousePressed

    private void jTbChinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbChinhMouseClicked
        // TODO add your handling code here:
        btnAddChinh.setEnabled(true);
    }//GEN-LAST:event_jTbChinhMouseClicked

    private void jTbPhuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbPhuMouseClicked
        // TODO add your handling code here:
        btnAddPhu.setEnabled(true);
    }//GEN-LAST:event_jTbPhuMouseClicked

    private void jTbNuocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbNuocMouseClicked
        btnAddNuoc.setEnabled(true);
    }//GEN-LAST:event_jTbNuocMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }
    public void CapNhatTien(){
        if(gh.tbGiohang.getRowCount()!=0)
            btnThanhtoan.setEnabled(true);
        else
            btnThanhtoan.setEnabled(false);
        int tien = 0;
        for(int i = 0; i<gh.tbGiohang.getRowCount();i++){
         int gia = Integer.parseInt(gh.tbGiohang.getValueAt(i, 2).toString());
         int sl = Integer.parseInt(gh.tbGiohang.getValueAt(i, 3).toString());
         long thanhtien = gia*sl;
          tien += thanhtien;
          
        }
        SetTien(Integer.toUnsignedLong(tien));
    }
    
    
    public void SetTien(long tien){
    DecimalFormat formatter = (DecimalFormat) NumberFormat.getInstance(Locale.CANADA);
    DecimalFormatSymbols symbols = formatter.getDecimalFormatSymbols();
    symbols.setGroupingSeparator(' ');
    formatter.setDecimalFormatSymbols(symbols);
    tongtien = tien;
    lbTien.setText(formatter.format(tien));
    }
    public void MenuBtn_Clicked(String c){
        switch(c){
            case "order": {
            menuOrder.setBackground(new Color(240,240,240));
            isClicked=1;
            menuManager.setBackground(new Color(220,40,56));
            menuSys.setBackground(new Color(220,40,56));
            }
            break;
            case "manager": {
            menuManager.setBackground(new Color(240,240,240));
            isClicked=2;
            menuOrder.setBackground(new Color(220,40,56));
            menuSys.setBackground(new Color(220,40,56));
            }
            break;
            case "sys": {
            menuSys.setBackground(new Color(240,240,240));
            isClicked=3;
            menuOrder.setBackground(new Color(220,40,56));
            menuManager.setBackground(new Color(220,40,56));
            }
            break;
        }
    }
    
    public void updateTb() throws SQLException{
        tbMonchinh.setRowCount(0);
        tbMonphu.setRowCount(0);
        tbNuoc.setRowCount(0);
        MonChinh();
        MonPhu();
        Nuoc();
    }
    protected void MonChinh() throws SQLException{

        ResultSet rs = sp.getMon(1);
        ResultSetMetaData rsmd = rs.getMetaData();
        
        tbMonchinh.setColumnCount(rsmd.getColumnCount()-1);
        try { 
            while(rs.next()){ // nếu còn đọc tiếp được một dòng dữ liệu
            String rows[] = new String[5];
            rows[0] = rs.getString(1); // lấy dữ liệu tại cột số 1 (ứng với mã hàng)
            rows[1] = rs.getString(3);
            rows[2] = rs.getString(4);
            rows[3] = rs.getString(5);
            tbMonchinh.addRow(rows); // đưa dòng dữ liệu vào tableModel 
            //mỗi lần có sự thay đổi dữ liệu ở tableModel thì Jtable sẽ tự động update 
        }
        }
        catch (SQLException e) {
        } 
            
}
    protected void MonPhu() throws SQLException{
        ResultSet rs = sp.getMon(2);
        ResultSetMetaData rsmd = rs.getMetaData();
        
        tbMonphu.setColumnCount(rsmd.getColumnCount()-1);
        try { 
            while(rs.next()){ // nếu còn đọc tiếp được một dòng dữ liệu
            String rows[] = new String[5];
            rows[0] = rs.getString(1); // lấy dữ liệu tại cột số 1 (ứng với mã hàng)
            rows[1] = rs.getString(3);
            rows[2] = rs.getString(4);
            rows[3] = rs.getString(5);
            tbMonphu.addRow(rows); // đưa dòng dữ liệu vào tableModel 
            //mỗi lần có sự thay đổi dữ liệu ở tableModel thì Jtable sẽ tự động update 
            }
        }
        catch (SQLException e) {
        } 
            
}
    protected void Nuoc() throws SQLException{
        ResultSet rs = sp.getMon(3);
        ResultSetMetaData rsmd = rs.getMetaData();
        
        tbNuoc.setColumnCount(rsmd.getColumnCount()-1);
        try { 
            while(rs.next()){ // nếu còn đọc tiếp được một dòng dữ liệu
            String rows[] = new String[5];
            rows[0] = rs.getString(1); // lấy dữ liệu tại cột số 1 (ứng với mã hàng)
            rows[1] = rs.getString(3);
            rows[2] = rs.getString(4);
            rows[3] = rs.getString(5);
            tbNuoc.addRow(rows); // đưa dòng dữ liệu vào tableModel 
            //mỗi lần có sự thay đổi dữ liệu ở tableModel thì Jtable sẽ tự động update 
            }
        }
        catch (SQLException e) {
        } 
            
}

    
    public class MetroLookAndFeel extends BasicButtonUI {

        // This could be computed properties, where the border color
        // is determined based on other properties
        private String mau;
        private Color co;
        private Border focusBorder = new CompoundBorder(new LineBorder(Color.DARK_GRAY, 3), new EmptyBorder(7, 13, 7, 14));
        private Border unfocusedBorder = new EmptyBorder(10, 14, 10, 14);
        
        public String Mau(String c){
            c = c.toLowerCase();
            this.mau = c;
            return this.mau;
        } 
        //@Override
        public void installDefaults(AbstractButton b) {
            String m = this.mau;
            super.installDefaults(b);
            Font f = new Font("Segoe UI", Font.PLAIN, 20);
            //co = new Color(0x000000);
            switch(m){
                case "do":
                    co = new Color(220,40,56);
                    break;
                case "cam":
                    co = new Color(255,153,102);
                    break;
                case "xanh":
                    co = new Color(51,153,255);
                    break;
                case "dodam":
                    co = new Color(204,0,51);
                    break;
                case "trang":
                    co = new Color(255,255,255);
                    break;
                case "":
                    co = new Color(0,0,0);
            }
            b.setFont(f);
            
            b.setContentAreaFilled(false);
            b.setFocusPainted(false);
            // This seems like an oddity...
            b.setFocusable(false);
            b.setForeground(Color.BLACK);
//            b.setBorder(BorderFactory.createEmptyBorder(10, 14, 10, 14));
            b.setBorder(unfocusedBorder);
        }

        @Override
        public void installListeners(AbstractButton b) {
            super.installListeners(b);
            b.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseEntered(MouseEvent e) {
                    ((JButton)e.getSource()).setBackground(Color.white);
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    ((JButton)e.getSource()).setBackground(co);
                }                
            });
        }

    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton btnAddChinh;
    protected javax.swing.JButton btnAddNuoc;
    protected javax.swing.JButton btnAddPhu;
    protected javax.swing.JButton btnCapnhat;
    protected javax.swing.JButton btnHuy;
    protected javax.swing.JButton btnThanhtoan;
    protected javax.swing.ButtonGroup buttonGroup1;
    protected javax.swing.JButton closeBtn;
    protected javax.swing.JLabel displayName;
    protected javax.swing.JLabel jLabel1;
    protected javax.swing.JLabel jLabel10;
    protected javax.swing.JLabel jLabel11;
    protected javax.swing.JLabel jLabel2;
    protected javax.swing.JLabel jLabel3;
    protected javax.swing.JLabel jLabel4;
    protected javax.swing.JLabel jLabel5;
    protected javax.swing.JLabel jLabel6;
    protected javax.swing.JLabel jLabel7;
    protected javax.swing.JLabel jLabel8;
    protected javax.swing.JLabel jLabel9;
    protected javax.swing.JLayeredPane jLayeredPane1;
    protected javax.swing.JPanel jPanel2;
    protected javax.swing.JPanel jPanel3;
    protected javax.swing.JPanel jPanel4;
    protected javax.swing.JPanel jPanel7;
    protected javax.swing.JSeparator jSeparator1;
    protected javax.swing.JTabbedPane jTabbedPane1;
    protected javax.swing.JTable jTbChinh;
    protected javax.swing.JTable jTbNuoc;
    protected javax.swing.JTable jTbPhu;
    protected javax.swing.JLabel lbTien;
    protected javax.swing.JPanel menuLogout;
    protected javax.swing.JPanel menuManager;
    protected javax.swing.JPanel menuOrder;
    protected javax.swing.JPanel menuSys;
    protected javax.swing.JButton minimizeBtn;
    protected javax.swing.JPanel panelChinh;
    protected javax.swing.JPanel panelNuoc;
    protected javax.swing.JPanel panelPhu;
    // End of variables declaration//GEN-END:variables
}
