/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fckfood;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.AbstractButton;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;
import javax.swing.plaf.basic.BasicButtonUI;
import javax.swing.table.DefaultTableModel;
import models.ThucDon;
import models.User;

/**
 *
 * @author NhokKiZ
 */
public class Manager extends javax.swing.JFrame {

    
     String uname ="";
    String uid;
    ThucDon td = new ThucDon();
    User ur = new User();
    public DefaultTableModel tbThucdon = new DefaultTableModel();
    public DefaultTableModel tbNhanvien = new DefaultTableModel();
    /**
     * Creates new form Manager
     */
    public Manager() throws SQLException {
        this.uname = User.name();
        this.uid = User.userName();
        initComponents();
        getAllSP();
        getAllNV();
    }

    int chuotX;
    int chuotY;
    int isClicked = 2;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        displayName = new javax.swing.JLabel();
        menuSys = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        menuOrder = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        menuManager = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        menuLogout = new javax.swing.JPanel();
        labellogout = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        minimizeBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        String spcol[] = {"Mã sản phẩm","Loại","Tên món","Đơn giá","Số lượng tồn"};
        jPanelqlySP = new javax.swing.JPanel();
        cbLoai = new javax.swing.JComboBox<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTbThucdon = new javax.swing.JTable();
        labelthemsp = new javax.swing.JLabel();
        labeltenmon = new javax.swing.JLabel();
        txtTenmon = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        labeldongia = new javax.swing.JLabel();
        txtSl = new javax.swing.JTextField();
        labelsoluong = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jPaneltimkiem = new javax.swing.JPanel();
        jLabeltimkiem = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        rdTen = new javax.swing.JRadioButton();
        rdLoai = new javax.swing.JRadioButton();
        rdMa = new javax.swing.JRadioButton();
        btnSearch = new javax.swing.JButton();
        btnThucdon = new javax.swing.JButton();
        cbsearchLoai = new javax.swing.JComboBox<>();
        btnHuy = new javax.swing.JButton();
        String nvcol[] = {"Username","Tên nhân viên","Năm sinh","Số điện thoại","Email","Chức vụ"};
        jPanelqlNV = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbNV = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtTennv = new javax.swing.JTextField();
        cbNgay = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        cbThang = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        txtNam = new javax.swing.JTextField();
        txtSdt = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnThemNV = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        cbRole = new javax.swing.JComboBox<>();
        btnSuaNV = new javax.swing.JButton();
        btnXoaNV = new javax.swing.JButton();
        btnHuyNV = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtTimNV = new javax.swing.JTextField();
        btnTimNV = new javax.swing.JToggleButton();
        btnTimNV1 = new javax.swing.JToggleButton();
        jPanelTK = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MetroLookAndFeel ui = new MetroLookAndFeel();

        jPanel3.setBackground(new java.awt.Color(220, 40, 56));
        jPanel3.setToolTipText("");
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 714));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Xin chào");

        displayName.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        displayName.setForeground(new java.awt.Color(255, 255, 255));
        displayName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        displayName.setText("admin");
        displayName.setText(uname);

        menuSys.setBackground(new java.awt.Color(220, 40, 56));
        menuSys.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        menuSys.setToolTipText("");
        menuSys.setPreferredSize(new java.awt.Dimension(310, 70));
        menuSys.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSysMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuSysMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuSysMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Hệ thống");

        javax.swing.GroupLayout menuSysLayout = new javax.swing.GroupLayout(menuSys);
        menuSys.setLayout(menuSysLayout);
        menuSysLayout.setHorizontalGroup(
            menuSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuSysLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(115, 115, 115))
        );
        menuSysLayout.setVerticalGroup(
            menuSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuSysLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuOrder.setBackground(new java.awt.Color(220, 40, 56));
        menuOrder.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        menuOrder.setToolTipText("");
        menuOrder.setPreferredSize(new java.awt.Dimension(338, 70));
        menuOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuOrderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuOrderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuOrderMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Order món ăn");
        jLabel4.setFocusable(false);

        javax.swing.GroupLayout menuOrderLayout = new javax.swing.GroupLayout(menuOrder);
        menuOrder.setLayout(menuOrderLayout);
        menuOrderLayout.setHorizontalGroup(
            menuOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addGap(115, 115, 115))
        );
        menuOrderLayout.setVerticalGroup(
            menuOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" FCKFOOD");
        jLabel1.setAlignmentX(200.0F);
        jLabel1.setAlignmentY(100.0F);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel1.setBounds(5, 10, 631, 36);
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        menuManager.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        menuManager.setToolTipText("");
        menuManager.setPreferredSize(new java.awt.Dimension(310, 70));
        menuManager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuManagerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuManagerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuManagerMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Quản lý");

        javax.swing.GroupLayout menuManagerLayout = new javax.swing.GroupLayout(menuManager);
        menuManager.setLayout(menuManagerLayout);
        menuManagerLayout.setHorizontalGroup(
            menuManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuManagerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(115, 115, 115))
        );
        menuManagerLayout.setVerticalGroup(
            menuManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuManagerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Developed by Kiz with ♥");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("® Client");

        menuLogout.setBackground(new java.awt.Color(255, 153, 102));
        menuLogout.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        menuLogout.setToolTipText("");
        menuLogout.setPreferredSize(new java.awt.Dimension(310, 70));
        menuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuLogoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuLogoutMousePressed(evt);
            }
        });

        labellogout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labellogout.setText("Logout");

        javax.swing.GroupLayout menuLogoutLayout = new javax.swing.GroupLayout(menuLogout);
        menuLogout.setLayout(menuLogoutLayout);
        menuLogoutLayout.setHorizontalGroup(
            menuLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labellogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(115, 115, 115))
        );
        menuLogoutLayout.setVerticalGroup(
            menuLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labellogout, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuManager, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                    .addComponent(menuSys, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(displayName, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(menuOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(50, 50, 50)
                .addComponent(jLabel3)
                .addGap(10, 10, 10)
                .addComponent(displayName)
                .addGap(40, 40, 40)
                .addComponent(menuOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(menuManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(menuSys, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menuLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(220, 40, 56));
        jPanel4.setPreferredSize(new java.awt.Dimension(960, 48));

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        minimizeBtn.setBackground(new java.awt.Color(220, 40, 56));
        minimizeBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        minimizeBtn.setText("_");
        ui.Mau("trang");
        minimizeBtn.setUI(ui);
        minimizeBtn.setMaximumSize(new java.awt.Dimension(43, 35));
        minimizeBtn.setMinimumSize(new java.awt.Dimension(43, 35));
        minimizeBtn.setPreferredSize(new java.awt.Dimension(43, 35));
        minimizeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeBtnActionPerformed(evt);
            }
        });
        jPanel2.add(minimizeBtn);

        closeBtn.setBackground(new java.awt.Color(255, 51, 51));
        closeBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        closeBtn.setText("X");
        ui.Mau("do");
        closeBtn.setUI(ui);
        closeBtn.setToolTipText("");
        closeBtn.setBorderPainted(false);
        closeBtn.setMaximumSize(new java.awt.Dimension(43, 35));
        closeBtn.setMinimumSize(new java.awt.Dimension(43, 35));
        closeBtn.setPreferredSize(new java.awt.Dimension(43, 35));
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        jPanel2.add(closeBtn);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(973, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane6.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane6.setForeground(new java.awt.Color(0, 0, 255));
        jTabbedPane6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jPanelqlySP.setBackground(new java.awt.Color(255, 255, 255));

        cbLoai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Món chính", "Món ăn kèm", "Nước" }));

        jTbThucdon.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTbThucdon.setModel(tbThucdon);
        jTbThucdon.setRowHeight(24);
        jTbThucdon.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTbThucdon.setDefaultEditor(Object.class, null);
        tbThucdon.setColumnIdentifiers(spcol);
        jTbThucdon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTbThucdonMouseReleased(evt);
            }
        });
        jTbThucdon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTbThucdonKeyPressed(evt);
            }
        });
        jScrollPane7.setViewportView(jTbThucdon);

        labelthemsp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelthemsp.setText("Thêm sản phẩm :");

        labeltenmon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labeltenmon.setText("Tên món :");

        labeldongia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labeldongia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labeldongia.setText("Đơn giá :");

        labelsoluong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelsoluong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelsoluong.setText("Số lượng :");

        btnThem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setEnabled(false);
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnXoa.setText("Xoá");
        btnXoa.setEnabled(false);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jPaneltimkiem.setBackground(new java.awt.Color(255, 255, 255));
        jPaneltimkiem.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabeltimkiem.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jLabeltimkiem.setText("Tìm kiếm sản phẩm");

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
        });

        rdTen.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdTen);
        rdTen.setText("Tên");

        rdLoai.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdLoai);
        rdLoai.setText("Loại");
        rdLoai.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdLoaiItemStateChanged(evt);
            }
        });

        rdMa.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdMa);
        rdMa.setSelected(true);
        rdMa.setText("Mã sản phẩm");

        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnSearch.setText("Tìm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnThucdon.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnThucdon.setText("Hiện toàn bộ thực đơn");
        btnThucdon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThucdonActionPerformed(evt);
            }
        });

        cbsearchLoai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbsearchLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Món chính", "Món ăn kèm", "Nước" }));
        cbsearchLoai.setEnabled(false);
        cbsearchLoai.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbsearchLoaiItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPaneltimkiemLayout = new javax.swing.GroupLayout(jPaneltimkiem);
        jPaneltimkiem.setLayout(jPaneltimkiemLayout);
        jPaneltimkiemLayout.setHorizontalGroup(
            jPaneltimkiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneltimkiemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPaneltimkiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearch)
                    .addGroup(jPaneltimkiemLayout.createSequentialGroup()
                        .addComponent(rdMa)
                        .addGap(18, 18, 18)
                        .addComponent(rdTen)
                        .addGap(18, 18, 18)
                        .addComponent(rdLoai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbsearchLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneltimkiemLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabeltimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPaneltimkiemLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnThucdon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPaneltimkiemLayout.setVerticalGroup(
            jPaneltimkiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneltimkiemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabeltimkiem)
                .addGap(18, 18, 18)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPaneltimkiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdTen)
                    .addComponent(rdLoai)
                    .addComponent(rdMa)
                    .addComponent(cbsearchLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPaneltimkiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThucdon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnHuy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnHuy.setText("Huỷ");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelqlySPLayout = new javax.swing.GroupLayout(jPanelqlySP);
        jPanelqlySP.setLayout(jPanelqlySPLayout);
        jPanelqlySPLayout.setHorizontalGroup(
            jPanelqlySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelqlySPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelqlySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7)
                    .addGroup(jPanelqlySPLayout.createSequentialGroup()
                        .addGroup(jPanelqlySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelqlySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(labelthemsp)
                                .addGroup(jPanelqlySPLayout.createSequentialGroup()
                                    .addComponent(labeltenmon)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTenmon, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelqlySPLayout.createSequentialGroup()
                                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelqlySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanelqlySPLayout.createSequentialGroup()
                                    .addComponent(labeldongia)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelqlySPLayout.createSequentialGroup()
                                    .addComponent(labelsoluong)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtSl, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jPaneltimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 493, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelqlySPLayout.setVerticalGroup(
            jPanelqlySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelqlySPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelqlySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelqlySPLayout.createSequentialGroup()
                        .addComponent(labelthemsp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelqlySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labeltenmon)
                            .addComponent(txtTenmon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelqlySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labeldongia)
                            .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelqlySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelsoluong)
                            .addComponent(txtSl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelqlySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPaneltimkiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane6.addTab(" Quản lý cửa hàng ", jPanelqlySP);

        jPanelqlNV.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTbNV.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTbNV.setModel(tbNhanvien);
        jTbNV.setRowHeight(24);
        jTbNV.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTbNV.setDefaultEditor(Object.class, null);
        tbNhanvien.setColumnIdentifiers(nvcol);
        jTbNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTbNVMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTbNV);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Quản lý nhân viên ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Tên nhân viên : ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Ngày sinh :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("SĐT : ");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Email : ");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Username : ");

        txtUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsernameKeyTyped(evt);
            }
        });

        txtTennv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTennv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTennvKeyTyped(evt);
            }
        });

        cbNgay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbNgay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel15.setText("/");

        cbThang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbThang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("/");

        txtNam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtSdt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSdtKeyTyped(evt);
            }
        });

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEmail.setNextFocusableComponent(cbRole);

        btnThemNV.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnThemNV.setText("Thêm");
        btnThemNV.setNextFocusableComponent(btnSuaNV);
        btnThemNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNVActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Chức vụ : ");

        cbRole.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Nhân viên" }));
        cbRole.setNextFocusableComponent(btnThemNV);

        btnSuaNV.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnSuaNV.setText("Sửa");
        btnSuaNV.setEnabled(false);
        btnSuaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaNVActionPerformed(evt);
            }
        });

        btnXoaNV.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnXoaNV.setText("Xoá");
        btnXoaNV.setEnabled(false);
        btnXoaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNVActionPerformed(evt);
            }
        });

        btnHuyNV.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnHuyNV.setText("Huỷ");
        btnHuyNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyNVActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setMaximumSize(new java.awt.Dimension(600, 46));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 46));

        jLabel17.setText("Tìm nhân viên :");

        txtTimNV.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        btnTimNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTimNV.setText("Tìm");

        btnTimNV1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTimNV1.setText("Hiện toàn bộ nhân viên");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTimNV, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTimNV, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTimNV1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTimNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimNV, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimNV1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelqlNVLayout = new javax.swing.GroupLayout(jPanelqlNV);
        jPanelqlNV.setLayout(jPanelqlNVLayout);
        jPanelqlNVLayout.setHorizontalGroup(
            jPanelqlNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelqlNVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelqlNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelqlNVLayout.createSequentialGroup()
                        .addGroup(jPanelqlNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelqlNVLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmail))
                            .addGroup(jPanelqlNVLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9)
                            .addGroup(jPanelqlNVLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelqlNVLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTennv))
                            .addGroup(jPanelqlNVLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(25, 25, 25)
                                .addComponent(cbNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNam, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelqlNVLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(10, 10, 10)
                                .addComponent(txtSdt)))
                        .addGap(63, 63, 63)
                        .addGroup(jPanelqlNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelqlNVLayout.createSequentialGroup()
                                .addComponent(btnThemNV, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSuaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnXoaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btnHuyNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelqlNVLayout.setVerticalGroup(
            jPanelqlNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelqlNVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelqlNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelqlNVLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(13, 13, 13)
                        .addGroup(jPanelqlNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelqlNVLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel14))
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelqlNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelqlNVLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel10))
                            .addComponent(txtTennv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelqlNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNam)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbThang)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbNgay)
                            .addComponent(jLabel11))
                        .addGap(12, 12, 12)
                        .addGroup(jPanelqlNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelqlNVLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel12))
                            .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanelqlNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelqlNVLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel13))
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanelqlNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)))
                    .addGroup(jPanelqlNVLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelqlNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnXoaNV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSuaNV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnThemNV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(btnHuyNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(11, 11, 11))
        );

        jTabbedPane6.addTab(" Quản lý nhân viên ", jPanelqlNV);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanelTKLayout = new javax.swing.GroupLayout(jPanelTK);
        jPanelTK.setLayout(jPanelTKLayout);
        jPanelTKLayout.setHorizontalGroup(
            jPanelTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelTKLayout.setVerticalGroup(
            jPanelTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab(" Thống kê ", jPanelTK);

        jLayeredPane1.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jTabbedPane6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1061, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jTabbedPane6)))
                .addGap(1, 1, 1))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane6)
                .addContainerGap())
        );

        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DRAG_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        // Close Tool
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_closeBtnActionPerformed

    private void minimizeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeBtnActionPerformed
        // TODO add your handling code here:
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeBtnActionPerformed

    private void menuLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseExited
        menuLogout.setBackground(new Color(255,153,102));
    }//GEN-LAST:event_menuLogoutMouseExited

    private void menuLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseEntered
        // TODO add your handling code here:
        menuLogout.setBackground(new Color(221,91,37));
    }//GEN-LAST:event_menuLogoutMouseEntered

    private void menuLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseClicked
        Login lg = new Login();
        User.Logout();
        this.dispose();
        lg.show();
    }//GEN-LAST:event_menuLogoutMouseClicked

    private void menuManagerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuManagerMouseExited

        if(isClicked!=2)
        menuManager.setBackground(new Color(220,40,56));
    }//GEN-LAST:event_menuManagerMouseExited

    private void menuManagerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuManagerMouseEntered
        // TODO add your handling code here:
        if(isClicked!=2)
        menuManager.setBackground(new Color(177,40,56));
    }//GEN-LAST:event_menuManagerMouseEntered

    private void menuManagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuManagerMouseClicked
        MenuBtn_Clicked("manager");
        //jLayeredPane1.show();
    }//GEN-LAST:event_menuManagerMouseClicked

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        chuotX = evt.getX();
        chuotY = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        int toadoX = evt.getXOnScreen();
        int toadoY = evt.getYOnScreen();
        this.setLocation(toadoX - chuotX, toadoY - chuotY);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void menuOrderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuOrderMouseExited
        if(isClicked!=1)
        menuOrder.setBackground(new Color(220,40,56));
    }//GEN-LAST:event_menuOrderMouseExited

    private void menuOrderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuOrderMouseEntered
        // TODO add your handling code here:
        if(isClicked!=1)
        menuOrder.setBackground(new Color(177,40,56));
    }//GEN-LAST:event_menuOrderMouseEntered

    private void menuOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuOrderMouseClicked
        // TODO add your handling code here:

        MenuBtn_Clicked("order");
        MainMenu menu;
        menu = new MainMenu(); //jLayeredPane1.show();
        menu.show();
        this.dispose();
    }//GEN-LAST:event_menuOrderMouseClicked

    private void menuSysMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSysMouseExited
        if(isClicked!=3)
        menuSys.setBackground(new Color(220,40,56));
    }//GEN-LAST:event_menuSysMouseExited

    private void menuSysMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSysMouseEntered
        if(isClicked!=3)
        menuSys.setBackground(new Color(177,40,56));
    }//GEN-LAST:event_menuSysMouseEntered

    private void menuSysMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSysMouseClicked
        // TODO add your handling code here:
        MenuBtn_Clicked("sys");
        //this.setVisible(false);
        //new Login().setVisible(true);
    }//GEN-LAST:event_menuSysMouseClicked

    private void menuLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMousePressed
        // TODO add your handling code here:
        menuLogout.setBackground(new Color(255,208,132));
    }//GEN-LAST:event_menuLogoutMousePressed

    private void btnHuyNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyNVActionPerformed
        txtUsername.setText("");
        txtTennv.setText("");
        txtSdt.setText("");
        txtEmail.setText("");
        cbNgay.setSelectedIndex(0);
        cbThang.setSelectedIndex(0);
        txtNam.setText("");
        cbRole.setSelectedIndex(0);
        btnSuaNV.setEnabled(false);
        btnXoaNV.setEnabled(false);
        btnThemNV.setEnabled(true);
        cbNgay.enable();
        cbThang.enable();
        txtNam.enable();
    }//GEN-LAST:event_btnHuyNVActionPerformed

    private void btnXoaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNVActionPerformed
        if(!"".equals(SelectedRowNV())){
            String uid = SelectedRowNV();
            int sure;
            sure = JOptionPane.showConfirmDialog(this,"\n Bạn có chắc sẽ xoá "+uid+" \n\n","Comfirm delete row",JOptionPane.YES_NO_OPTION);
            if(sure==JOptionPane.YES_OPTION){
                try {
                    int row =jTbNV.getSelectedRow();
                    ur.DelNV(uid);
                    tbNhanvien.removeRow(row);
                    JOptionPane.showMessageDialog(this,"\n Đã xoá :"+uid+" \n\n","Xoá dữ liệu thành công",1);
                    btnHuyNV.doClick();
                }catch (SQLException ex) {

                }
            }else if(sure==JOptionPane.NO_OPTION){;}
        }
    }//GEN-LAST:event_btnXoaNVActionPerformed

    private void btnSuaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaNVActionPerformed

        int row = jTbNV.getSelectedRow();
        String uid = tbNhanvien.getValueAt(row, 0).toString();
        uid = txtUsername.getText();
        String name = txtTennv.getText();
        String phone = txtSdt.getText();
        String mail = txtEmail.getText();
        int role = cbRole.getSelectedIndex() + 1;
        int sure = JOptionPane.showConfirmDialog(this,"\n Bạn có chắc sẽ sửa tài khoản "+uid+" \n\n","Comfirm editting",JOptionPane.YES_NO_OPTION);
        if(sure==JOptionPane.YES_OPTION){
            try {
                ur.UpdateNV(uid, name, phone, mail, role);
                JOptionPane.showMessageDialog(this,"\n Tài khoản "+uid+" đã được cập nhật \n\n","Cập nhật dữ liệu thành công",1);
                tbNhanvien.setRowCount(0);
                getAllNV();
            }catch (SQLException ex) {
                System.out.println(ex);
            }
        }else if(sure==JOptionPane.NO_OPTION){;}
    }//GEN-LAST:event_btnSuaNVActionPerformed

    private void btnThemNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNVActionPerformed
        //JOptionPane.showMessageDialog(this,"\n Nhập sai định dạng \n\n","Lỗi dữ liệu",JOptionPane.ERROR_MESSAGE);
        ur.setNgay(cbNgay.getItemAt(cbNgay.getSelectedIndex()));
        ur.setThang(cbThang.getItemAt(cbThang.getSelectedIndex()));
        ur.setNam(txtNam.getText());
        try {
            if (ur.ThemNV(txtUsername.getText(), txtTennv.getText(),txtSdt.getText(), txtEmail.getText(), (cbRole.getSelectedIndex()+1))){
                JOptionPane.showMessageDialog(this,"\n Dữ liệu đã thêm thành công \n\n","Complete querry",1);
                tbNhanvien.setRowCount(0);
                getAllNV();
                jTbNV.setRowSelectionInterval(0, jTbNV.getRowCount()-1);
            }
            else{
                JOptionPane.showMessageDialog(this,"\n Nhập thông tin không chính xác \n\n","Lỗi dữ liệu",JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (SQLException ex) {}
    }//GEN-LAST:event_btnThemNVActionPerformed

    private void txtSdtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSdtKeyTyped
        int len = txtSdt.getText().length();
        char testChar = evt.getKeyChar();
        if( len > 11 || !(Character.isDigit(testChar)))
        evt.consume();
    }//GEN-LAST:event_txtSdtKeyTyped

    private void txtTennvKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTennvKeyTyped
        char testChar = evt.getKeyChar();
        if((Character.isDigit(testChar)))
        evt.consume();
    }//GEN-LAST:event_txtTennvKeyTyped

    private void txtUsernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyTyped
        int len = txtUsername.getText().length();
        char testChar = evt.getKeyChar();
        if( len >= 20 || (!(Character.isDigit(testChar)) & !(Character.isLetter(testChar))))
        evt.consume();
    }//GEN-LAST:event_txtUsernameKeyTyped

    private void jTbNVMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbNVMouseReleased
        SelectedRowNV();
    }//GEN-LAST:event_jTbNVMouseReleased

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        txtTenmon.setText("");
        txtGia.setText("");
        txtSl.setText("");
        cbLoai.setSelectedIndex(0);
        btnThucdon.doClick();
        this.btnThem.setEnabled(true);
        this.btnSua.setEnabled(false);
        this.btnXoa.setEnabled(false);
    }//GEN-LAST:event_btnHuyActionPerformed

    private void cbsearchLoaiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbsearchLoaiItemStateChanged
        btnSearch.doClick();
    }//GEN-LAST:event_cbsearchLoaiItemStateChanged

    private void btnThucdonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThucdonActionPerformed
        // TODO add your handling code here:
        tbThucdon.setRowCount(0);
        try {
            getAllSP();
        } catch (SQLException ex) {}
    }//GEN-LAST:event_btnThucdonActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        if(rdLoai.isSelected()){
            try {
                tbThucdon.setRowCount(0);
                searchSP(3);
            }catch (SQLException ex) {}
        }else if(rdTen.isSelected()){
            try {
                tbThucdon.setRowCount(0);
                searchSP(2);
            }catch (SQLException ex) {}
        }
        else{
            try {
                tbThucdon.setRowCount(0);
                searchSP(1);
            }catch (SQLException ex) {}
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void rdLoaiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdLoaiItemStateChanged
        // TODO add your handling code here:
        if(rdLoai.isSelected()){
            cbsearchLoai.setEnabled(true);
            txtSearch.setEnabled(false);
        }
        else{
            cbsearchLoai.setEnabled(false);
            txtSearch.setEnabled(true);
        }
    }//GEN-LAST:event_rdLoaiItemStateChanged

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            btnSearch.doClick();
        }
    }//GEN-LAST:event_txtSearchKeyPressed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if(!"".equals(SelectedRow())){
            String masp = SelectedRow();
            int sure;
            sure = JOptionPane.showConfirmDialog(this,"\n Bạn có chắc sẽ xoá sản phẩm "+masp+" \n\n","Comfirm delete row",JOptionPane.YES_NO_OPTION);
            if(sure==JOptionPane.YES_OPTION){
                try {
                    int row =jTbThucdon.getSelectedRow();
                    td.DelSanpham(masp);
                    tbThucdon.removeRow(row);
                    JOptionPane.showMessageDialog(this,"\n Đã xoá sản phẩm :"+masp+" \n\n","Xoá dữ liệu thành công",1);
                    btnHuy.doClick();
                }catch (SQLException ex) {

                }
            }else if(sure==JOptionPane.NO_OPTION){;}
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        String masp;
        int row = jTbThucdon.getSelectedRow();
        masp = tbThucdon.getValueAt(row, 0).toString();
        System.out.println(masp);
        String ten = txtTenmon.getText();
        int loai = cbLoai.getSelectedIndex()+1;
        int gia = Integer.parseInt(txtGia.getText());
        int sl = Integer.parseInt(txtSl.getText());
        int sure = JOptionPane.showConfirmDialog(this,"\n Bạn có chắc sẽ sửa sản phẩm "+masp+" \n\n","Comfirm editting",JOptionPane.YES_NO_OPTION);
        if(sure==JOptionPane.YES_OPTION){
            try {
                td.UpdateSanpham(masp, loai, ten, gia, sl);
                JOptionPane.showMessageDialog(this,"\n Sản phẩm "+masp+" đã được cập nhật \n\n","Cập nhật dữ liệu thành công",1);
                tbThucdon.setRowCount(0);
                getAllSP();
            }catch (SQLException ex) {
                System.out.println(ex);
            }
        }else if(sure==JOptionPane.NO_OPTION){;}

    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        String masp="";
        try {
            String oldma = td.currentLast();
            int newma;
            newma = Integer.parseInt(oldma.replaceAll("\\D+",""));
            masp="FF"+String.format("%03d", (newma+1));

        } catch (SQLException ex) {

        }
        try {
            td.InsertSanpham(masp, cbLoai.getSelectedIndex()+1, txtTenmon.getText() , Long.parseLong(txtGia.getText()), Integer.parseInt(txtSl.getText()));
            JOptionPane.showMessageDialog(this,"\n Dữ liệu đã thêm thành công \n\n","Complete querry",1);
            tbThucdon.setRowCount(0);
            getAllSP();
            jTbThucdon.setRowSelectionInterval(0, jTbThucdon.getRowCount()-1);

        } catch (Exception ex) {
            System.out.println(ex);
            JOptionPane.showMessageDialog(this,"\n Nhập sai định dạng \n\n","Lỗi dữ liệu",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnThemActionPerformed

    private void jTbThucdonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTbThucdonKeyPressed
        int keyCode = evt.getKeyCode();
        switch( keyCode ) {
            case KeyEvent.VK_UP:
            SelectedRow();
            break;
            case KeyEvent.VK_DOWN:
            SelectedRow();
            break;
        }
    }//GEN-LAST:event_jTbThucdonKeyPressed

    private void jTbThucdonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbThucdonMouseReleased
        SelectedRow();
    }//GEN-LAST:event_jTbThucdonMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Manager().setVisible(true);
                } catch (SQLException ex) {
                }
            }
        });
    }
    
    public void searchSP(int rd) throws SQLException{
        ResultSet rs=null;
        switch(rd){
            case 1: 
                rs = td.searchMon("masp", txtSearch.getText()); 
                break;
            case 2:
                rs = td.searchMon("tensp", txtSearch.getText());
                break;
            case 3:
                String a = String.valueOf(cbsearchLoai.getSelectedIndex()+1);
                rs = td.searchMon("loai",a);
                break;
        }        
         while(rs.next()){ // nếu còn đọc tiếp được một dòng dữ liệu
            String rows[] = new String[5];
            rows[0] = rs.getString(1); 
            switch(rs.getInt(2)){
                case 1:
                    rows[1] = "Món chính";
                    break;
                case 2:
                    rows[1] = "Món ăn kèm";
                    break;
                case 3:
                    rows[1] = "Nước";
                    break;
            }
            rows[2] = rs.getString(3);
            rows[3] = rs.getString(4);
            rows[4] = rs.getString(5);
            tbThucdon.addRow(rows); // đưa dòng dữ liệu vào tableModel 
        }
    }
    
    public void getAllSP() throws SQLException{
        
        ResultSet rs = td.Thucdon();
        ResultSetMetaData rsmd = rs.getMetaData();
        try { 
            while(rs.next()){ // nếu còn đọc tiếp được một dòng dữ liệu
            String rows[] = new String[5];
            rows[0] = rs.getString(1); 
            switch(rs.getInt(2)){
                case 1:
                    rows[1] = "Món chính";
                    break;
                case 2:
                    rows[1] = "Món ăn kèm";
                    break;
                case 3:
                    rows[1] = "Nước";
                    break;
            }
            rows[2] = rs.getString(3);
            rows[3] = rs.getString(4);
            rows[4] = rs.getString(5);
            tbThucdon.addRow(rows); // đưa dòng dữ liệu vào tableModel 
        }
        }
        catch (SQLException e) {
        } 
    }
    
    public void getAllNV() throws SQLException{
        
        ResultSet rs = ur.getAllNV();
        try { 
            while(rs.next()){ // nếu còn đọc tiếp được một dòng dữ liệu
            String rows[] = new String[6];
            rows[0] = rs.getString(1); 
            rows[1] = rs.getString(2);
            rows[2] = rs.getString(3);
            rows[3] = rs.getString(4);
            rows[4] = rs.getString(5);
            rows[5] = rs.getString(6);
            tbNhanvien.addRow(rows); 
        }
        }
        catch (SQLException e) {
        } 
    }
    
    
    public void MenuBtn_Clicked(String c){
        switch(c){
            case "order": {
            menuOrder.setBackground(new Color(240,240,240));
            isClicked=1;
            menuManager.setBackground(new Color(220,40,56));
            menuSys.setBackground(new Color(220,40,56));
            }
            break;
            case "manager": {
            menuManager.setBackground(new Color(240,240,240));
            isClicked=2;
            menuOrder.setBackground(new Color(220,40,56));
            menuSys.setBackground(new Color(220,40,56));
            }
            break;
            case "sys": {
            menuSys.setBackground(new Color(240,240,240));
            isClicked=3;
            menuOrder.setBackground(new Color(220,40,56));
            menuManager.setBackground(new Color(220,40,56));
            }
            break;
        }
    }
    
    public String SelectedRowNV(){
    int row =jTbNV.getSelectedRow();
    String username = "";
    String DoB="";
    if(row>=0){
        this.btnSuaNV.setEnabled(true);
        this.btnXoaNV.setEnabled(true);
        this.btnThemNV.setEnabled(false);
        this.cbNgay.disable();
        this.cbThang.disable();
        this.txtNam.disable();
        try{
            //Lay chi so dong dang chon
            String uid=(jTbNV.getModel().getValueAt(row,0)).toString();
            ResultSet rs= ur.getUser(uid);
            if(rs.next())//Neu co du lieu
            {   
                username = rs.getString(1);
                txtUsername.setText(rs.getString(1));
                txtTennv.setText(rs.getString(2));
                ur.RegExDoB(rs.getString(3));
                cbNgay.setSelectedIndex(Integer.parseInt(ur.getNgay())-1);
                cbThang.setSelectedIndex(Integer.parseInt(ur.getThang())-1);
                txtNam.setText(ur.getNam());
                txtSdt.setText(rs.getString(4));
                txtEmail.setText(rs.getString(5));
                switch (rs.getString(6)){
                    case "admin":
                        cbRole.setSelectedIndex(0);
                        break;
                    case "nhân viên":
                        cbRole.setSelectedIndex(1);
                        break;
                };
            }
        }
        catch (SQLException e) {
        }
    }
        return username;
    }
    
    public String SelectedRow(){
    int row =jTbThucdon.getSelectedRow();
    String masp = "";
    if(row>=0){
        this.btnSua.setEnabled(true);
        this.btnXoa.setEnabled(true);
        this.btnThem.setEnabled(false);
        try{
            //Lay chi so dong dang chon
            String ma=(jTbThucdon.getModel().getValueAt(row,0)).toString();
            ResultSet rs= td.getMontheoma(ma);//Goi ham lay du lieu theo ma sp
            if(rs.next())//Neu co du lieu
            {   
                masp = rs.getString("masp");
                txtTenmon.setText(rs.getString("tensp"));
                txtGia.setText(rs.getString("dongia"));
                txtSl.setText(rs.getString("soluong"));
                cbLoai.setSelectedIndex(rs.getInt("loai")-1);
            }
            
        }
        catch (SQLException e) {
        }
    }
        return masp;
    }
    
   
    
    public class MetroLookAndFeel extends BasicButtonUI {

        // This could be computed properties, where the border color
        // is determined based on other properties
        private String mau;
        private Color co;
        private Border focusBorder = new CompoundBorder(new LineBorder(Color.DARK_GRAY, 3), new EmptyBorder(7, 13, 7, 14));
        private Border unfocusedBorder = new EmptyBorder(10, 14, 10, 14);
        
        public String Mau(String c){
            c = c.toLowerCase();
            this.mau = c;
            return this.mau;
        } 
        //@Override
        public void installDefaults(AbstractButton b) {
            String m = this.mau;
            super.installDefaults(b);
            Font f = new Font("Segoe UI", Font.PLAIN, 20);
            //co = new Color(0x000000);
            switch(m){
                case "do":
                    co = new Color(220,40,56);
                    break;
                case "cam":
                    co = new Color(255,153,102);
                    break;
                case "xanh":
                    co = new Color(51,153,255);
                    break;
                case "dodam":
                    co = new Color(204,0,51);
                    break;
                case "trang":
                    co = new Color(255,255,255);
                    break;
                case "":
                    co = new Color(0,0,0);
            }
            b.setFont(f);
            
            b.setContentAreaFilled(false);
            b.setFocusPainted(false);
            // This seems like an oddity...
            b.setFocusable(false);
            b.setForeground(Color.BLACK);
//            b.setBorder(BorderFactory.createEmptyBorder(10, 14, 10, 14));
            b.setBorder(unfocusedBorder);
        }

        @Override
        public void installListeners(AbstractButton b) {
            super.installListeners(b);
            b.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseEntered(MouseEvent e) {
                    ((JButton)e.getSource()).setBackground(Color.white);
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    ((JButton)e.getSource()).setBackground(co);
                }                
            });
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnHuyNV;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnSuaNV;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemNV;
    private javax.swing.JButton btnThucdon;
    private javax.swing.JToggleButton btnTimNV;
    private javax.swing.JToggleButton btnTimNV1;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaNV;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbLoai;
    private javax.swing.JComboBox<String> cbNgay;
    private javax.swing.JComboBox<String> cbRole;
    private javax.swing.JComboBox<String> cbThang;
    private javax.swing.JComboBox<String> cbsearchLoai;
    private javax.swing.JButton closeBtn;
    private javax.swing.JLabel displayName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabeltimkiem;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelTK;
    private javax.swing.JPanel jPanelqlNV;
    private javax.swing.JPanel jPanelqlySP;
    private javax.swing.JPanel jPaneltimkiem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTbNV;
    private javax.swing.JTable jTbThucdon;
    private javax.swing.JLabel labeldongia;
    private javax.swing.JLabel labellogout;
    private javax.swing.JLabel labelsoluong;
    private javax.swing.JLabel labeltenmon;
    private javax.swing.JLabel labelthemsp;
    private javax.swing.JPanel menuLogout;
    private javax.swing.JPanel menuManager;
    private javax.swing.JPanel menuOrder;
    private javax.swing.JPanel menuSys;
    private javax.swing.JButton minimizeBtn;
    private javax.swing.JRadioButton rdLoai;
    private javax.swing.JRadioButton rdMa;
    private javax.swing.JRadioButton rdTen;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtNam;
    private javax.swing.JTextField txtSdt;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSl;
    private javax.swing.JTextField txtTenmon;
    private javax.swing.JTextField txtTennv;
    private javax.swing.JTextField txtTimNV;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
